# Generated by Django 6.1 on 2026-08-24 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='tenants.organization')),
            ],
            options={
                'db_table': 'dashboards_dashboard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('filter_type', models.CharField(choices=[('date', 'Date'), ('text', 'Text'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('number_range', 'Number Range'), ('date_range', 'Date Range')], max_length=20)),
                ('target_column', models.CharField(max_length=500)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='dashboards.dashboard')),
            ],
            options={
                'db_table': 'dashboards_filter',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI'), ('table', 'Table'), ('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('heatmap', 'Heatmap')], max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('position_x', models.PositiveSmallIntegerField(default=0)),
                ('position_y', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=6)),
                ('height', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard')),
            ],
            options={
                'db_table': 'dashboards_widget',
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
