# Generated by Django 5.0.7 on 2026-08-24 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("executive_summary", models.TextField(blank=True)),
                (
                    "report_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("xlsx", "XLSX"), ("csv", "CSV"), ("html", "HTML")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=[("draft", "Draft"), ("generated", "Generated")], default="draft", max_length=20),
                ),
                ("generated_file_path", models.CharField(blank=True, max_length=1000)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="tenants.organization"),
                ),
            ],
            options={"db_table": "reports_report", "ordering": ["-created_at"]},
        ),
    ]
